"""`agent-squad init` — vendor the template into a consumer repo."""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from importlib import resources
from pathlib import Path

SQUAD_DIR_NAME = ".agent_squad"
PLUGIN_DIR_NAME = ".claude-plugin"


def register(sub: argparse._SubParsersAction) -> None:
    p = sub.add_parser(
        "init",
        help="Vendor the squad template into the current repo (creates .agent_squad/).",
        description=(
            "Copies bundled agents, skills, scripts, and a starter config.toml into "
            "<repo>/.agent_squad/. Generates the Claude Code plugin manifests so the "
            "vendored agents and skills register on /reload-plugins."
        ),
    )
    p.add_argument(
        "--target",
        type=Path,
        default=Path.cwd(),
        help="Target repo root (default: cwd).",
    )
    p.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing .agent_squad/ files (config.toml is never overwritten).",
    )
    p.set_defaults(func=run)


def run(args: argparse.Namespace) -> int:
    target: Path = args.target.resolve()
    if not target.is_dir():
        print(f"agent-squad: target is not a directory: {target}", file=sys.stderr)
        return 2

    squad_dir = target / SQUAD_DIR_NAME
    plugin_dir = target / PLUGIN_DIR_NAME

    template_root = _template_root()

    print(f"Vendoring squad into {squad_dir}")
    _copy_template(template_root, squad_dir, force=args.force)
    _write_config_example(squad_dir)
    _write_plugin_manifests(target, plugin_dir, squad_dir)

    print()
    print("Done. Next steps:")
    print(f"  1. Edit {squad_dir / 'config.toml.example'} and save as config.toml.")
    print("  2. In Claude Code, run:")
    print("       /plugin marketplace add .")
    print("       /plugin install agent-squad")
    print("     (one-time per repo; the vendored agents register as `agent-squad:*`).")
    print("  3. Commit .agent_squad/ and .claude-plugin/ so teammates and remote runners share the squad.")
    return 0


def _template_root() -> Path:
    """Locate the bundled template/ directory regardless of installed-vs-editable."""
    pkg_root = resources.files("agent_squad")
    return Path(str(pkg_root / "template"))


def _copy_template(src: Path, dst: Path, *, force: bool) -> None:
    dst.mkdir(parents=True, exist_ok=True)
    for child in src.iterdir():
        if child.name == "config.toml.example":
            continue  # handled separately so we never clobber a real config.toml
        target = dst / child.name
        if target.exists() and not force:
            print(f"  skip {target.relative_to(dst.parent)} (already exists; --force to overwrite)")
            continue
        if child.is_dir():
            if target.exists():
                shutil.rmtree(target)
            shutil.copytree(child, target)
        else:
            shutil.copy2(child, target)
        print(f"  + {target.relative_to(dst.parent)}")


def _write_config_example(squad_dir: Path) -> None:
    src = _template_root() / "config.toml.example"
    target_example = squad_dir / "config.toml.example"
    shutil.copy2(src, target_example)
    real_config = squad_dir / "config.toml"
    if not real_config.exists():
        shutil.copy2(src, real_config)
        print(f"  + {real_config.relative_to(squad_dir.parent)} (starter; edit before use)")
    else:
        print(f"  keep {real_config.relative_to(squad_dir.parent)} (untouched)")


def _write_plugin_manifests(repo_root: Path, plugin_dir: Path, squad_dir: Path) -> None:
    """Generate the Claude Code plugin manifests so vendored content auto-registers.

    Two files:
      <repo>/.claude-plugin/marketplace.json  -> single-plugin marketplace pointing at .agent_squad
      <repo>/.agent_squad/.claude-plugin/plugin.json -> the plugin's own manifest

    Users run `/plugin marketplace add .` once; thereafter `/reload-plugins` picks up edits.
    """
    plugin_dir.mkdir(parents=True, exist_ok=True)
    marketplace = {
        "name": "agent-squad-local",
        "metadata": {
            "description": "Locally-vendored agent-squad. Generated by `agent-squad init`; do not edit by hand.",
            "version": "0.1.0",
        },
        "plugins": [
            {
                "name": "agent-squad",
                "source": "./.agent_squad",
                "description": "Vendored agent squad — ticket-manager, managers, workers, and supporting skills.",
                "version": "0.1.0",
            }
        ],
    }
    (plugin_dir / "marketplace.json").write_text(json.dumps(marketplace, indent=2) + "\n")
    print(f"  + {(plugin_dir / 'marketplace.json').relative_to(repo_root)}")

    inner_plugin_dir = squad_dir / PLUGIN_DIR_NAME
    inner_plugin_dir.mkdir(parents=True, exist_ok=True)
    plugin_manifest = {
        "name": "agent-squad",
        "description": "Vendored agent squad. Source of truth lives in .agent_squad/agents/, .agent_squad/skills/, .agent_squad/managers/.",
        "version": "0.1.0",
    }
    (inner_plugin_dir / "plugin.json").write_text(json.dumps(plugin_manifest, indent=2) + "\n")
    print(f"  + {(inner_plugin_dir / 'plugin.json').relative_to(repo_root)}")
